return {
  { 'ellisonleao/glow.nvim', cmd = 'Glow' },
  { 'famiu/bufdelete.nvim' },
  {
    'folke/todo-comments.nvim',
    config = true,
    dependencies = { 'nvim-lua/plenary.nvim' },
  },
  { 'karb94/neoscroll.nvim', opts = { easing_function = 'sine' } },
  {
    'kylechui/nvim-surround',
    event = 'VeryLazy',
    opts = {
      keymaps = {
        insert = '<C-g>c',
        insert_line = '<C-g>C',
        normal = 'yc',
        normal_cur = 'ycc',
        normal_line = 'yC',
        normal_cur_line = 'yCC',
        visual = 'C',
        visual_line = 'gC',
        delete = 'dc',
        change = 'cc',
        change_line = 'cC',
      },
    },
  },
  { 'monaqa/dial.nvim', keys = { '<c-a>', '<c-x>' } },
  { 'NvChad/nvim-colorizer.lua', config = true },
  { 'numToStr/Comment.nvim', config = true, event = { 'BufRead' } },
  { 'nvim-lua/plenary.nvim' },
  -- { 'stevearc/dressing.nvim', event = 'VeryLazy' },
  { 'windwp/nvim-autopairs', config = true },
}
